CREATE TABLE employees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    role VARCHAR(100),
    salary NUMERIC(10, 2)
);

INSERT INTO employees (name, email, role, salary) VALUES
('Casey CEO', 'casey.ceo@insureco.com', 'Chief Executive Officer', 153195.45),
('Morgan COO', 'morgan.coo@insureco.com', 'Chief Operating Officer', 201061.59),
('Riley CFO', 'riley.cfo@insureco.com', 'Chief Financial Officer', 150779.55),
('Jordan CTO', 'jordan.cto@insureco.com', 'Chief Technology Officer', 208555.00),
('Sydney CISO', 'sydney.ciso@insureco.com', 'Chief Information Security Officer', 200154.32),
('Alex Admin', 'alex.admin@insureco.com', 'Database Admin', 109794.98),
('Taylor DBA', 'taylor.dba@insureco.com', 'Database Admin', 95172.43),
('Oscar Johnson', 'oscar.johnson@insureco.com', 'Claims Specialist', 69889.15),
('Tina Taylor', 'tina.taylor@insureco.com', 'Claims Specialist', 77729.97),
('Uma Khan', 'uma.khan@insureco.com', 'Sales Agent', 90264.17),
('Mona Khan', 'mona.khan@insureco.com', 'Customer Service Rep', 59896.19),
('Charlie Smith', 'charlie.smith@insureco.com', 'Policy Analyst', 67175.54),
('Nina Patel', 'nina.patel@insureco.com', 'Insurance Agent', 58216.27),
('Oscar Owens', 'oscar.owens@insureco.com', 'Underwriter', 104562.03),
('Tina Young', 'tina.young@insureco.com', 'Insurance Agent', 74925.53),
('Nina Vargas', 'nina.vargas@insureco.com', 'Actuary', 107956.49),
('Alice Garcia', 'alice.garcia@insureco.com', 'Policy Analyst', 78132.36),
('Steve White', 'steve.white@insureco.com', 'Underwriter', 80417.97),
('David Quinn', 'david.quinn@insureco.com', 'Policy Analyst', 57160.77),
('Nina Quinn', 'nina.quinn@insureco.com', 'Customer Service Rep', 92882.16),
('Charlie Quinn', 'charlie.quinn@insureco.com', 'Underwriter', 79629.91),
('Zack Usman', 'zack.usman@insureco.com', 'Risk Manager', 69423.67),
('Oscar Quinn', 'oscar.quinn@insureco.com', 'Risk Manager', 97118.42),
('Bob Zimmerman', 'bob.zimmerman@insureco.com', 'Risk Manager', 108602.58),
('Helen Owens', 'helen.owens@insureco.com', 'Insurance Agent', 62794.50),
('Grace Harris', 'grace.harris@insureco.com', 'Underwriter', 63182.76),
('Tina Roberts', 'tina.roberts@insureco.com', 'Insurance Agent', 76382.39),
('Nina Johnson', 'nina.johnson@insureco.com', 'Underwriter', 109328.22),
('Charlie Owens', 'charlie.owens@insureco.com', 'Customer Service Rep', 72509.92),
('Uma Harris', 'uma.harris@insureco.com', 'Insurance Agent', 73114.80),
('David Zimmerman', 'david.zimmerman@insureco.com', 'Insurance Agent', 54789.58),
('Helen Usman', 'helen.usman@insureco.com', 'Actuary', 94545.59),
('Quinn Vargas', 'quinn.vargas@insureco.com', 'Policy Analyst', 55935.41),
('Leo Lee', 'leo.lee@insureco.com', 'Policy Analyst', 83846.32),
('Uma Usman', 'uma.usman@insureco.com', 'Claims Specialist', 95245.20),
('Nina Martinez', 'nina.martinez@insureco.com', 'Actuary', 55702.45),
('Alice Martinez', 'alice.martinez@insureco.com', 'Risk Manager', 75142.51),
('Jack Owens', 'jack.owens@insureco.com', 'Customer Service Rep', 87945.66),
('Xander Brown', 'xander.brown@insureco.com', 'Claims Specialist', 55072.87),
('Xander Evans', 'xander.evans@insureco.com', 'Claims Specialist', 56171.52),
('Helen Young', 'helen.young@insureco.com', 'Underwriter', 82492.11),
('Charlie Harris', 'charlie.harris@insureco.com', 'Sales Agent', 84822.95),
('Quinn Johnson', 'quinn.johnson@insureco.com', 'Underwriter', 87187.36),
('Eva Smith', 'eva.smith@insureco.com', 'Risk Manager', 70683.24),
('Mona Davis', 'mona.davis@insureco.com', 'Underwriter', 68791.42),
('Ian Ibrahim', 'ian.ibrahim@insureco.com', 'Claims Specialist', 107518.17),
('Victor Usman', 'victor.usman@insureco.com', 'Sales Agent', 94675.85),
('Eva Martinez', 'eva.martinez@insureco.com', 'Underwriter', 101289.65),
('Quinn Brown', 'quinn.brown@insureco.com', 'Sales Agent', 66890.25),
('Alice White', 'alice.white@insureco.com', 'Claims Specialist', 107625.01);
